import 'package:doc_appointment/controllers/main_controller.dart';
import 'package:doc_appointment/models/banners.dart';
import 'package:get/get.dart';

class BannerController extends GetxController {
  final _mainController = Get.find<MainController>();
  var currentIndex = 0.obs;

  List<Banners> get banners => _mainController.autogenerated?.banners ?? [];

  void updateIndex(int index) {
    currentIndex.value = index; // Actualizează indexul curent
  }
}
