import 'dart:math';

import 'package:doc_appointment/models/categories.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import 'main_controller.dart';

class CategoryController extends GetxController {
  var showAll = false.obs;
  final _mainController = Get.find<MainController>();

  List<Categories> get categories =>
      _mainController.autogenerated?.categories ?? [];

  toggleShowAll() {
    showAll.value = !showAll.value;
  }

  Color getColor() {
    final Random random = Random();
    return Color.fromARGB(
      255, // Opacity (100%)
      random.nextInt(256), // Red value (0-255)
      random.nextInt(256), // Green value (0-255)
      random.nextInt(256), // Blue value (0-255)
    );
  }
}
