import 'package:doc_appointment/models/nearby_centers.dart';
import 'package:get/get.dart';

import 'main_controller.dart';

class CenterController extends GetxController{
  final _mainController = Get.find<MainController>();

  List<NearbyCenters> get nearbyCenters => _mainController.autogenerated?.nearbyCenters ?? []; 

}