import 'dart:convert';

import 'package:doc_appointment/models/autogenerated.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';

class MainController extends GetxController{
  var isLoadig = false.obs;
  Autogenerated? autogenerated;

  @override
  Future<void> onInit()async{
    super.onInit();
    loadData();
  }

  loadData()async{
    isLoadig(true);
    try{
      String json = await rootBundle.loadString('assets/v1.json');
      var result = jsonDecode(json);
      autogenerated = Autogenerated.fromJson(result);
    }
    catch(e){
      print('Error while getting data: $e');
    }
    finally{
      isLoadig(false);
    }
  }

}